# Generated by Django 4.2.3 on 2024-01-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contatomodel',
            options={'ordering': ['-data'], 'verbose_name': 'Formulario de contato', 'verbose_name_plural': 'Formulario de contatos'},
        ),
        migrations.AddField(
            model_name='contatomodel',
            name='lido',
            field=models.BooleanField(blank=True, default=True, verbose_name='Lido'),
        ),
    ]
