# Generated by Django 4.2.3 on 2024-02-04 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('rua', models.CharField(max_length=100, verbose_name='Rua')),
                ('numero', models.CharField(max_length=10, verbose_name='Rua')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
            ],
        ),
        migrations.AlterModelOptions(
            name='reservamodel',
            options={'verbose_name': 'Reserva de banho', 'verbose_name_plural': 'Reserva de banho'},
        ),
        migrations.AddField(
            model_name='reservamodel',
            name='petshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.petshop'),
        ),
    ]
